# Generated by Django 4.2.27

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.mindmap


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0125_project_lead_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="mindmap_view",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Mindmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(blank=True, default="Untitled Mindmap")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=plane.db.models.mindmap.get_default_mindmap_data,
                    ),
                ),
                (
                    "access",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Private"), (0, "Public")], default=0
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=255)),
                ("archived_at", models.DateField(null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("view_props", models.JSONField(default=dict)),
                ("logo_props", models.JSONField(default=dict)),
                ("sort_order", models.FloatField(default=65535)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mindmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mindmaps",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mindmap",
                "verbose_name_plural": "Mindmaps",
                "db_table": "mindmaps",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectMindmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "mindmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_mindmaps",
                        to="db.mindmap",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_mindmaps",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_mindmaps",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Mindmap",
                "verbose_name_plural": "Project Mindmaps",
                "db_table": "project_mindmaps",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="mindmap",
            name="projects",
            field=models.ManyToManyField(
                related_name="mindmaps",
                through="db.ProjectMindmap",
                to="db.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmindmap",
            unique_together={("project", "mindmap", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="projectmindmap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "mindmap"),
                name="project_mindmap_unique_project_mindmap_when_deleted_at_null",
            ),
        ),
    ]
