# Generated by Django 4.2.27

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0126_mindmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuePage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_pages",
                        to="db.issue",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_issues",
                        to="db.page",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_project",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_workspace",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Page",
                "verbose_name_plural": "Issue Pages",
                "db_table": "issue_pages",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueMindmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_mindmaps",
                        to="db.issue",
                    ),
                ),
                (
                    "mindmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mindmap_issues",
                        to="db.mindmap",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_project",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_workspace",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Mindmap",
                "verbose_name_plural": "Issue Mindmaps",
                "db_table": "issue_mindmaps",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="pages",
            field=models.ManyToManyField(
                blank=True,
                related_name="issue_pages",
                through="db.IssuePage",
                to="db.page",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="mindmaps",
            field=models.ManyToManyField(
                blank=True,
                related_name="issue_mindmaps",
                through="db.IssueMindmap",
                to="db.mindmap",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuepage",
            unique_together={("issue", "page", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="issuepage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "page"),
                name="issue_page_unique_issue_page_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuemindmap",
            unique_together={("issue", "mindmap", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="issuemindmap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "mindmap"),
                name="issue_mindmap_unique_issue_mindmap_when_deleted_at_null",
            ),
        ),
    ]
