# Generated by Django 4.2.27

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.diagram


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0127_issue_page_mindmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="diagram_view",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(blank=True, default="Untitled Diagram")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=plane.db.models.diagram.get_default_diagram_data,
                    ),
                ),
                (
                    "access",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Private"), (0, "Public")], default=0
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=255)),
                ("archived_at", models.DateField(null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("view_props", models.JSONField(default=dict)),
                ("logo_props", models.JSONField(default=dict)),
                ("sort_order", models.FloatField(default=65535)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagrams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagrams",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagram",
                "verbose_name_plural": "Diagrams",
                "db_table": "diagrams",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectDiagram",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_diagrams",
                        to="db.diagram",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_diagrams",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_diagrams",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Diagram",
                "verbose_name_plural": "Project Diagrams",
                "db_table": "project_diagrams",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueDiagram",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_diagrams",
                        to="db.issue",
                    ),
                ),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagram_issues",
                        to="db.diagram",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_project",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_workspace",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Diagram",
                "verbose_name_plural": "Issue Diagrams",
                "db_table": "issue_diagrams",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="diagram",
            name="projects",
            field=models.ManyToManyField(
                related_name="diagrams",
                through="db.ProjectDiagram",
                to="db.project",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="diagrams",
            field=models.ManyToManyField(
                blank=True,
                related_name="issue_diagrams",
                through="db.IssueDiagram",
                to="db.diagram",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectdiagram",
            unique_together={("project", "diagram", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="projectdiagram",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "diagram"),
                name="project_diagram_unique_project_diagram_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuediagram",
            unique_together={("issue", "diagram", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="issuediagram",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "diagram"),
                name="issue_diagram_unique_issue_diagram_when_deleted_at_null",
            ),
        ),
    ]
