# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0128_diagram_issue_diagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="mindmap_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="diagram_view",
            field=models.BooleanField(default=False),
        ),
    ]
